// fetch GitHub repos
export const START_FETCHING_REPOS = "START_FETCHING_REPOS";
export const FETCHING_REPOS_SUCCESS = "FETCHING_REPOS_SUCCESS";
export const FETCHING_REPOS_FAIL = "FETCHING_REPOS_FAIL";
